### ISSUE TITLE
crash ao colar imagens

### ISSUE THREAD

**Issue by jaspior** [HighEloDevs/Analysis-Tool-for-Undergrad-Students#28]
**Describe the bug**
O ATUS fecha abruptamente quando se tenta colar imagem ao invés de números. Isso acontece muito quando o usuário salva o gráfico e esquece de selecionar novos dados antes de inseri-los no ATUS

**To Reproduce**
1 - copie qualquer imagem
2 - use o comando para colar (ctrl espaço ou ctrl b)

**Expected behavior**
A janela simplesmente fecha

**Suggestion**
Da mesma forma que o ATUS identifica que há texto nos dados dá área de transferência, ele poderia identificar se há imagens e avisar.

**Comment by GuiiFerrari** [comment]
Fixed in https://github.com/HighEloDevs/Analysis-Tool-for-Undergrad-Students/commit/2e0fdb5b021afd9e52008d0eead912326c717a4d

Thanks for reporting!
