### ISSUE TITLE
instalação linux

### ISSUE THREAD

**Issue by jaspior** [HighEloDevs/Analysis-Tool-for-Undergrad-Students#32]
**Describe the bug**
Problema em instalar o atus no ubuntu
![image (12)](https://github.com/HighEloDevs/Analysis-Tool-for-Undergrad-Students/assets/38392025/e60bb1f8-45ed-46c5-a1d4-74fc7a9a8235)

**Desktop (please complete the following information):**
-ubutnu 24.04

**Additional context**
aparentemente essa é a solução

https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-mana/75696359#75696359

**Comment by deividw** [comment]
Recomendo sempre instalar libs em ambientes virtuais com venv, por exemplo. Evita bagunçar com o python padrão do sistema
