### ISSUE TITLE
Instalação - MacOs Sonoma

### ISSUE THREAD

**Issue by AsdfXIX** [HighEloDevs/Analysis-Tool-for-Undergrad-Students#34]
Olá. Gostaria de ajuda quanto à instalação no MacOS. Quando baixo o arquivo ZIP, descomprimo-o e sigo as instruções de comandos do terminal, aparece o seguinte erro:

```
ERROR: Ignored the following yanked versions: 0.2.4.6
ERROR: Ignored the following versions that require a different python version: 1.0.5.7 Requires-Python >=3.7, <3.10; 1.1.0.0 Requires-Python >=3.7, <3.10; 1.2.0 Requires-Python >=3.7, <3.11; 1.2.2 Requires-Python >3.8, <3.12; 1.3.0 Requires-Python >3.8, <3.12
ERROR: Could not find a version that satisfies the requirement atus (from versions: none)
ERROR: No matching distribution found for atus
```

Sou pouco familiarizado com o funcionamento do terminal, então, se alguém puder ajudar, agradeço. Segue abaixo especificações do dispositivo:

Modelo: MacBook Air - 2019, Retina, 13 Polegadas,
macOS: Sonoma 14.7

**Comment by deividw** [comment]
@AsdfXIX Pode compartilhar, por gentileza, qual versão do python você possui instalado?
Você pode verificar a versão executando o seguinte comando no terminal: `python3 --version`

**Comment by AsdfXIX** [comment]
Boa tarde, @deividw. A versão é 3.12.4

**Comment by deividw** [comment]
@AsdfXIX Consegue instalar o python3.10 e testar com ele, por gentileza? o 3.12 ainda não é suportado, mas será em breve (hopefully)

**Comment by deividw** [comment]
adendo: 3.11 tbm é suportado

**Comment by AsdfXIX** [comment]
Consegui agora. Muito obrigado.
